server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: contract-service
  messages:
    encoding: UTF-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://localhost:1433;database=ContractDb;encrypt=false
    username: SA
    password: a123456B
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    hibernate:
      ddl-auto: update
#      database-platform: org.hibernate.dialect.Oracle12cDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 500
#        order_inserts: true
#        order_updates: true
    show-sql: true
#  data:
#    jdbc:
#      dialect: oracle
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: camunda-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

camunda:
  bpm:
#    authorization:
#      enabled: true
    admin-user:
      id: admin
      password: admin
    database:
      schema-update: true


logging:
  level:
    org:
      springframework:
        security: INFO
        web: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE